# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5c89018d47a3d8377a9c5e047ca6fb248b50a39ba96cc17f307c399a5a388e3a3b4cbdfc2f0a3cc3407868887cd41d94bde4115d90bf889d66d450ecd67aacd

test:
  secret_key_base: 4b87450eaed5f9a3a476248e666286c9456211df4087d5d94ba12fe646f482d1f7362f4269d10d83d25712b9c3e196ef73245ff8b7e6b6ea060b536fe56de9dd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
